import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import BlogLayout from "../../components/BlogLayout";
import { IBlog, ICategory } from "../../lib/interfaces/blog";
import { getAllPostIds, getPostData } from "../../lib/posts";

interface BlogCategoryProps {
    category: ICategory;
}

const BlogCategory: NextPage<BlogCategoryProps> = ({ category }) => {
    return (
        <BlogLayout>
            <Head>
                <title>{category.categoryName}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>adsada</main>
        </BlogLayout>
    );
};

export default BlogCategory;

export const getStaticPaths: GetStaticPaths = async () => {
    const paths = [
        "science",
        "technology",
        "mathematics",
        "computer-science",
    ].map((e) => {
        return "/categories/" + e;
    });

    return {
        paths,
        fallback: false,
    };
};

export const getStaticProps: GetStaticProps = async () => {
    const category = {
        id: "science",
        categoryName: "Science",
    };

    return {
        props: { category },
    };
};
