import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import BlogLayout from "../../components/BlogLayout";
import CategoryPreview from "../../components/CategoryPreview";
import { ICategory } from "../../lib/interfaces/blog";

interface CategoriesProps {
    categories: ICategory[];
}

const Categories: NextPage<CategoriesProps> = ({ categories }) => {
    return (
        <>
            <BlogLayout>
                <Head>
                    <title>Home</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main>
                    {categories.map((category) => {
                        return (
                            <CategoryPreview
                                category={category}
                                key={category.id}
                            />
                        );
                    })}
                </main>
            </BlogLayout>
        </>
    );
};

export default Categories;

export const getStaticProps: GetStaticProps = async () => {
    const categories = [
        {
            id: "science",
            categoryName: "Science",
        },
        {
            id: "technology",
            categoryName: "Technology",
        },
        {
            id: "mathematics",
            categoryName: "Mathematics",
        },
        {
            id: "computer-science",
            categoryName: "Computer Science",
        },
    ];
    return {
        props: {
            categories,
        },
    };
};
